---
title: "Statistics Project"
output: html_notebook
---


```{r}
# Load required packages
library(dplyr)
```
```{r}
# Generate example data
set.seed(123)  # to keep same values for later runs

```
```{r}
# Survey answers (4 possible answers: A, B, C, D)
answers <- c("A", "B", "C", "D")
```
```{r}
# Generate random probabilities
random_probs <- runif(length(answers))

# Normalize the probabilities so they sum to 1
random_probs <- random_probs / sum(random_probs)
```

```{r}
# Generate answers for those who witnessed a natural disaster
n_hurricane <- 10000
answers_hurricane <- sample(answers, n_hurricane, replace = TRUE, prob = random_probs)
```
```{r}
# Generate random probabilities
new_random_probs <- runif(length(answers))

# Normalize the probabilities so they sum to 1
new_random_probs <- new_random_probs / sum(new_random_probs)
```

```{r}
# Generate answers for those who did not witness a natural disaster
n_no_hurricane <- 10000
answers_no_hurricane <- sample(answers, n_no_hurricane, replace = TRUE, prob = new_random_probs)

```
```{r}
# Compute answers frequency
freq_hurricane <- table(answers_hurricane)
freq_no_hurricane <- table(answers_no_hurricane)
```
```{r}
freq_hurricane
```
```{r}
freq_no_hurricane
```
```{r}
# Convert frequencies to cumulative distributions
cdf_hurricane <- cumsum(freq_hurricane) / n_hurricane
cdf_no_hurricane <- cumsum(freq_no_hurricane) / n_no_hurricane
```
```{r}
cdf_hurricane
```
```{r}
cdf_no_hurricane
```

```{r}
# Kolmogorov-Smirnov test
ks_test <- ks.test(freq_hurricane, freq_no_hurricane)
print(ks_test)
```
```{r}
# Chi-square test
chi_square_test <- chisq.test(freq_hurricane, freq_no_hurricane)
print(chi_square_test)
```
```{r}
## Both the Kolmogorov-Smirnov test and Pearson's Chi-squared test suggest that there is no statistically significant difference between the distributions of freq_hurricane and freq_no_hurricane.
```
```{r}
# Join answers C and D to make the distribution more skewed
answers_skewed <- c("A", "B", "CD")
```
```{r}
# Function to join the two answers
join_answers <- function(answers) {
  answers <- as.character(answers)
  answers[answers == "C" | answers == "D"] <- "CD"
  return(answers)
}
```
```{r}
answers_hurricane_skewed <- join_answers(answers_hurricane)
answers_no_hurricane_skewed <- join_answers(answers_no_hurricane)
```
```{r}
# Compute new answers frequencies
freq_hurricane_skewed <- table(answers_hurricane_skewed)
freq_no_hurricane_skewed <- table(answers_no_hurricane_skewed)
```
```{r}
#  Convert frequencies to cumulative distributions
cdf_hurricane_skewed <- cumsum(freq_hurricane_skewed) / n_hurricane
cdf_no_hurricane_skewed <- cumsum(freq_no_hurricane_skewed) / n_no_hurricane
```
```{r}
# Kolmogorov-Smirnov test on skewed distributions
ks_test_skewed <- ks.test(freq_hurricane_skewed, freq_no_hurricane_skewed)
print(ks_test_skewed)
```
```{r}
# Chi-square test on skewed distributions
chi_square_test_skewed <- chisq.test(freq_hurricane_skewed, freq_no_hurricane_skewed)
print(chi_square_test_skewed)
```
```{r}
## The skewed distributions of the two groups (hurricane and no hurricane) are still similar and not distinguishable.
## Note that p-value of KS Test increased, while the one of Chi-squared decreased. This might denote that KS-test is indeed more robust when dealing with skewed distributions, as stated in the paper.
```
